const name = [
  "Lakshman Kumar",
  "Prakash Tiwari",
  "Rahul raj",
  "Abhisek verma",
  "Manish Dev",
  "Aarav",
  "Vivaan",
  "Aditya",
  "Vihaan",
  "Arjun",
  "Sai",
  "Krishna",
  "Ishaan",
  "Rohan",
  "Aryan",
  "Arnav",
  "Aarav Sharma",
  "Vivaan Kapoor",
  "Aditya",
  "Vihaan Patel",
  "Arjun Mehra",
  "Sai",
  "Krishna Iyer",
  "Ishaan Rao",
  "Rohan Gupta",
  "Aryan",
  "Arnav Singh",
  "Reyansh Agarwal",
  "Shaurya Joshi",
  "Atharv",
  "Ayaan",
  "Kabir",
  "Kian Malhotra",
  "Nirvaan",
  "Ananya Verma",
  "Riya",
  "Neha",
  "Pooja",
  "Sanya",
  "Aditi",
  "Aishwarya",
  "Tanvi Desai",
  "Meera",
  "Sana",
  "Naina",
  "Shruti",
  "Radhika",
  "Madhav Nair",
  "Aarav Sharma",
  "Vivaan Kapoor",
  "Vihaan Patel",
  "Arjun Mehra",
  "Krishna Iyer",
  "Ishaan Rao",
  "Rohan Gupta",
  "Arnav Singh",
  "Reyansh Agarwal",
  "Shaurya Joshi",
  "Kian Malhotra",
  "Tanvi Desai",
  "Madhav Nair",
  "Karthik Reddy",
  "Rajiv Bhatia",
  "Siddharth Chatterjee",
  "Priya Nair",
  "Ananya Verma",
  "Aarohi Saxena",
  "Ritika Sinha",
  "Niharika",
  "Swati",
  "Vikas",
  "Abhinav",
  "Kunal",
  "Rajesh",
  "Siddhi",
  "Ritu",
  "Gautam",
  "Mukul",
  "Nivedita",
  "Arushi",
  "Nikhil",
  "Shreya",
];

export function generateRandomName() {
  return name[Math.floor(Math.random() * name.length)];
}

const message = [
  "Amazing video yaar, keep it up!",
  "इस वीडियो ने मेरी बहुत मदद की।",
  "जल्दी से और वीडियो अपलोड कीजिए, इंतजार नहीं हो रहा।",
  "आपके चैनल से बहुत प्रेरणा मिलती है।",
  "आपकी आवाज़ बहुत अच्छी है।",
  "Bahut hi accha explain kiya aapne.",
  "Content is always top-notch!",
  "Is video ne mera din bana diya!",
  "वीडियो थोड़ा लंबा होता तो अच्छा लगता।",
  "बहुत ही इम्प्रेसिव वीडियो है।",
  "आपकी हर वीडियो में कुछ खास होता है।",
  "बहुत ही ज्ञानवर्धक वीडियो है।",
  "इस वीडियो ने मेरी समस्या का समाधान कर दिया।",
  "आपके वीडियो की क्वालिटी बहुत बढ़िया है।",
  "आपका हर वीडियो देखने लायक होता है।",
  "बहुत ही बढ़िया समझाया आपने।",
  "Bahut hi zabardast video banaya hai aapne!",
  "You're a natural at explaining things.",
  "Is video ka wait kar raha tha!",
  "Aapki baatein hamesha dil ko chhoti hain.",
  "Love your sense of humor!",
  "Koi doubt nahi raha after watching this.",
  "आपके चैनल से बहुत कुछ सीखने को मिलता है।",
  "क्या गजब का वीडियो है!",
  "आपकी बातें हमेशा दिल को छू जाती हैं।",
  "वीडियो की एडिटिंग बहुत शानदार है।",
  "आपका कंटेंट बहुत प्रेरणादायक है।",
  "ये वीडियो देखने के बाद सब क्लियर हो गया।",
  "बहुत ही अच्छी जानकारी दी आपने।",
  "वीडियो का प्रोडक्शन वैल्यू बहुत हाई है।",
  "आपकी मेहनत साफ दिखती है।",
  "वीडियो बहुत ही उपयोगी है।",
  "Great job bhai, bohot maza aaya.",
  "Your editing skills are amazing!",
  "Ye topic pehle samajh nahi aata tha, thanks!",
  "Aapke videos hamesha informative hote hain.",
  "Kya baat hai, aise hi content banate raho.",
  "This video is exactly what I needed.",
  "Superb content, as always!",
  "Aapke videos se hamesha kuch naya seekhne ko milta hai.",
  "Jaldi se next video upload karo!",
  "This was so helpful, thanks!",
  "Bhai, tumhara style alag hi level ka hai.",
  "Aapke channel se bohot kuch seekhne ko milta hai.",
  "Bahut hi acchi clarity se explain kiya hai.",
  "Can't wait for your next video!",
  "Video dekhke lagta hai, aapko bohot mehnat lagti hai.",
  "You nailed it again, awesome work!",
  "Aapka content seriously next level hai.",
  "क्या शानदार प्रेजेंटेशन है!",
  "आपके वीडियो देखने में हमेशा मजा आता है।",
  "Bahut hi accha concept explain kiya.",
  "Great work! Keep inspiring us.",
  "Kya mast video banaya hai yaar!",
  "This is so well explained, thank you!",
  "Bhai tumne toh kamaal kar diya!",
  "Aapki videos mein quality hamesha high hoti hai.",
  "Thanks for breaking it down so simply.",
  "Ye video sabko dekhna chahiye, bohot useful hai.",
  "You always deliver such quality content!",
  "Mujhe aapka approach bohot pasand aaya.",
  "Aapke videos ke bina kuch adhura lagta hai.",
  "This was exactly what I was looking for!",
  "Aapke har video se kuch naya seekhne ko milta hai.",
  "Kya amazing baat batai aapne, thanks!",
  "The way you explain is just awesome!",
  "Aapka editing game on point hai.",
  "Keep going, aapka content bohot inspiring hai!",
  "Hamesha aapke videos dekhke motivation milti hai.",
  "You made this topic so easy to understand!",
  "Aapki voice bohot soothing hai.",
  "Yeh video dekhne ke baad sab clear ho gaya.",
  "Great content, aapko zaroor subscribe karna chahiye.",
];

export function generateRandomText(length) {
  return message[Math.floor(Math.random() * message.length)];
}
